# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.CharField(default='http://www.volantio.com/images/team/jeremiah.jpg', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
