# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0004_auto_20170623_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='bio',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='person',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='person',
            name='github',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='person',
            name='hobbies',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
